server:
    port: 9090

spring:
    application:
        name: droolsSpring
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
    datasource:
        url: jdbc:mysql://127.0.0.1/test?userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: password
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true

    thymeleaf:
        cache: false
    redis:
        host: 49.4.114.32
        port: 6379
        password: zzl_redis