-- Kafka相关表创建SQL脚本

-- 1. 魔方表
CREATE TABLE IF NOT EXISTS `MAGIC_CUBE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `MAGIC_NAME` VARCHAR(100) NOT NULL COMMENT '魔方名称',
  `CREATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `VERSION` INT DEFAULT 1 COMMENT '版本号',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_MAGIC_NAME` (`MAGIC_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='魔方表';

-- 2. Kafka主题表
CREATE TABLE IF NOT EXISTS `KAFKA_TOPIC` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主题ID',
  `TOPIC_NAME` VARCHAR(200) NOT NULL COMMENT '主题名称',
  `CREATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `VERSION` INT DEFAULT 1 COMMENT '版本号',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_TOPIC_NAME` (`TOPIC_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Kafka主题表';

-- 3. Kafka用户管理表
CREATE TABLE IF NOT EXISTS `KAFKA_MNG_USER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `USER_NAME` VARCHAR(100) NOT NULL COMMENT '用户名称',
  `USER_PWD` VARCHAR(200) DEFAULT '123456' COMMENT '用户密码',
  `CREATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `VERSION` INT DEFAULT 1 COMMENT '版本号',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USER_NAME` (`USER_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Kafka用户管理表';

-- 4. Kafka主题权限表
CREATE TABLE IF NOT EXISTS `KAFKA_TOPIC_PERMISSION` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `MAGIC_ID` BIGINT NOT NULL COMMENT '魔方ID',
  `TOPIC_ID` BIGINT NOT NULL COMMENT '主题ID',
  `USER_ID` BIGINT NOT NULL COMMENT '用户ID',
  `PERMISSION_TYPE` VARCHAR(50) NOT NULL COMMENT '用户权限',
  `CREATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `VERSION` INT DEFAULT 1 COMMENT '版本号',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_MAGIC_TOPIC_USER` (`MAGIC_ID`, `TOPIC_ID`, `USER_ID`),
  KEY `IDX_MAGIC_ID` (`MAGIC_ID`),
  KEY `IDX_TOPIC_ID` (`TOPIC_ID`),
  KEY `IDX_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Kafka主题权限表';

-- 插入测试魔方数据
INSERT INTO `MAGIC_CUBE` (`MAGIC_NAME`) VALUES 
('测试魔方1'),
('测试魔方2'),
('生产魔方');
